name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * SUN'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get Latest Ubuntu LTS Version and Code Name
        run: |
            ubuntu_version=$(curl -s https://endoflife.date/ubuntu | awk '/LTS/ {print $1; exit}')
            ubuntu_codename=$(curl -s https://endoflife.date/ubuntu | awk '/LTS/ {print tolower($2); exit}' | sed s/\'//)
            echo "Latest Ubuntu LTS Version: $ubuntu_version"
            echo "Latest Ubuntu LTS Code Name: $ubuntu_codename"
            echo "ubuntu_version=$ubuntu_version" >> "$GITHUB_ENV"
            echo "ubuntu_codename=$ubuntu_codename" >> "$GITHUB_ENV"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            TAG=${{ env.ubuntu_codename }}
          platforms:
            linux/amd64,
            linux/arm64
          push: true
          tags:
            scottyhardy/docker-remote-desktop:latest,
            scottyhardy/docker-remote-desktop:ubuntu-${{ env.ubuntu_codename }},
            scottyhardy/docker-remote-desktop:ubuntu-${{ env.ubuntu_version }}
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: scottyhardy/docker-remote-desktop
