name: test

on:
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get Latest Ubuntu LTS Code Name
        run: |
          ubuntu_codename=$(curl -s https://endoflife.date/ubuntu | awk '/LTS/ {print tolower($2); exit}' | sed s/\'//)
          echo "Latest Ubuntu LTS Code Name: $ubuntu_codename"
          echo "ubuntu_codename=$ubuntu_codename" >> "$GITHUB_ENV"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            TAG=${{ env.ubuntu_codename }}
